/* DML Script to load data into  the Athlete table
*/
USE Soccer

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(1, 'Christen', 'Press', 33);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(2, 'Alex', 'Morgan', 32);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(3, 'Mallory', 'Pugh', 23);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(4, 'Sydney', 'Leroux', 31);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(5, 'Rose', 'Lavelle', 26);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(6, 'Luciano', 'Acosta', 27);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(7, 'Jake', 'Morris', 23);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(8, 'Wil', 'Trapp', 29);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(9, 'Rodrigo', 'Schlegel', 25);

INSERT INTO ATHLETE(ATHLETE_ID, ATHLETE_FIRST_NAME, ATHLETE_LAST_NAME, ATHLETE_AGE) 
VALUES(10, 'Lewis', 'Morgan', 25);