/*DML Script to load data into athlete game stats table
*/

USE Soccer

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (5, 1, 15, 0, 0, 0, 0, 0, 0, 1, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (5, 2, 60, 0, 1, 2, 1, 0, 0, 1, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (5, 3, 89, 1, 0, 1, 1, 0, 0, 0, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (1, 4, 90, 0, 0, 7, 4, 0, 0 , 0, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (1, 2, 88, 0, 0, 3, 1, 3, 0, 1, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (1, 6, 80, 0, 0, 5, 1, 4, 0, 0, 1);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (1, 7, 90, 1, 0, 5, 3, 1, 0, 1, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (3, 8, 90, 1, 0, 5, 3, 1, 0, 1, 0);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (3, 9, 70, 0, 0, 2, 0, 4, 0, 0, 1);

INSERT INTO ATHLETE_GAME_STATS (ATHLETE_ID, GAME_ID, GAME_TIME, GOALS, ASSISTS, SHOTS, SHOTS_ON_GOAL, CORNER_KICKS,
OFFSIDES, FOULS_COMMITTED,FOULS_SUSTAINED) VALUES (3, 10, 84, 2, 0, 5, 3, 6, 0, 1, 0);