/*Execute 2nd. Creates Tables with relations.
*/
Use Soccer

CREATE TABLE TEAM (
	TEAM_ID INT NOT NULL,
	TEAM_NAME VARCHAR(100) NOT NULL,
	TEAM_CITY VARCHAR(100) NOT NULL,
	TEAM_STATE VARCHAR(100) NOT NULL,
	TEAM_HEAD_COACH VARCHAR(100) NOT NULL,
	PRIMARY KEY(TEAM_ID)
);

CREATE TABLE ATHLETE (
	ATHLETE_ID INT NOT NULL,
	ATHLETE_FIRST_NAME VARCHAR(100) NOT NULL,
	ATHLETE_LAST_NAME VARCHAR(100) NOT NULL,
	ATHLETE_AGE INT NOT NULL,
	PRIMARY KEY(ATHLETE_ID)
);

CREATE TABLE TEAM_ROSTER (
	TEAM_ID INT NOT NULL,
	ATHLETE_ID INT NOT NULL,
	ATHLETE_CITY VARCHAR(100) NOT NULL,
	ATHLETE_STATE VARCHAR(100),
	ATHLETE_COUNTRY VARCHAR(100) NOT NULL,
	ATHLETE_POSITION VARCHAR(100) NOT NULL,
	ATHLETE_NUMBER INT NOT NULL,
	ATHLETE_HEIGHT VARCHAR(20) NOT NULL,
	ATHLETE_DOB VARCHAR(20) NOT NULL
	PRIMARY KEY(TEAM_ID),
	FOREIGN KEY (ATHLETE_ID) REFERENCES ATHLETE(ATHLETE_ID)
);

CREATE TABLE [STATS] (
	ATHLETE_ID INT NOT NULL,
	NUM_APPEARANCES INT NOT NULL,
	GOALS INT NOT NULL,
	ASSISTS INT NOT NULL,
	PRIMARY KEY(ATHLETE_ID)
);

CREATE TABLE SEASON_GAMES (
	GAME_ID INT NOT NULL,
	GAME_LOCATION VARCHAR(100) NOT NULL,
	SCORE VARCHAR(100) NOT NULL,
	HOME_TEAM_ID INT NOT NULL,
	AWAY_TEAM_ID INT NOT NULL,
	TOURNAMENT_NAME VARCHAR(100),
	GAME_DATE VARCHAR(100),
	PRIMARY KEY(GAME_ID)
);

CREATE TABLE ATHLETE_GAME_STATS (
	ATHLETE_ID INT NOT NULL,
	GAME_ID INT NOT NULL,
	GAME_TIME INT NOT NULL,
	GOALS INT NOT NULL,
	ASSISTS INT NOT NULL,
	SHOTS INT NOT NULL,
	SHOTS_ON_GOAL INT NOT NULL,
	CORNER_KICKS INT NOT NULL,
	OFFSIDES INT NOT NULL,
	FOULS_COMMITTED INT NOT NULL,
	FOULS_SUSTAINED INT NOT NULL,
);