USE Soccer
GO

/* Procedure that shows  all of the games that the athlete Mallory pugh has played in along with her game stats
*/
CREATE PROCEDURE [Mallory Pugh]
AS
SELECT SEASON_GAMES.GAME_DATE, SEASON_GAMES.GAME_LOCATION, ATHLETE_GAME_STATS.GAME_TIME,
ATHLETE_GAME_STATS.GOALS, ATHLETE_GAME_STATS.ASSISTS, ATHLETE_GAME_STATS.SHOTS, 
ATHLETE_GAME_STATS.SHOTS_ON_GOAL, ATHLETE_GAME_STATS.CORNER_KICKS, ATHLETE_GAME_STATS.OFFSIDES,
ATHLETE_GAME_STATS.FOULS_COMMITTED, ATHLETE_GAME_STATS.FOULS_SUSTAINED
FROM SEASON_GAMES, ATHLETE_GAME_STATS, ATHLETE
WHERE ATHLETE.ATHLETE_FIRST_NAME = 'Mallory'
AND ATHLETE.ATHLETE_ID = ATHLETE_GAME_STATS.ATHLETE_ID
AND ATHLETE_GAME_STATS.GAME_ID = SEASON_GAMES.GAME_ID;