/* Queries to show the relations in the database
*/
USE Soccer
GO

/*Query to show all of the primary and foreign keys in the database
*/
SELECT * FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE;

/*Query to show FK/PK in the table Athlete
*/
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'ATHLETE';

/*Query to show FK/PK in the table Athlete Game Stats
*/
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'ATHLETE_GAME_STATS';

/*Query to show FK/PK in the table Season Games
*/
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'SEASON_GAMES';

/*Query to show FK/PK in the table Stats
*/
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'STATS';

/*Query to show FK/PK in the table Team
*/
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'TEAM';

/*Query to show FK/PK in the table Team Roster
*/
SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_NAME = 'TEAM_ROSTER';