/*DML Script to load data into stats table
*/

USE Soccer

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (1,4, 1, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (2,3, 2, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (3, 4, 4, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (4, 3, 0, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (5, 3, 1, 1);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (6, 6, 1, 2);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (7, 3, 0, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (8, 4, 0, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (9, 5, 0, 0);

INSERT INTO [STATS] (ATHLETE_ID, NUM_APPEARANCES, GOALS, ASSISTS)
VALUES (10, 5, 3, 1);