/* DML Script to load data into the Team Roster table
*/

USE Soccer

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_STATE, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (1,1, 'Los Angeles', 'CA', 'USA', 'Attacker', 23, '5 foot 6', '12/29/1988');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_STATE, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (2,2, 'San Dimas', 'CA', 'USA', 'Attacker', 13, '5 foot 6', '7/2/1989');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_STATE, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (3,3, 'Highlands Ranch', 'CA', 'USA', 'Attacker', 9, '5 foot 4', '4/29/1998');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (4,4, 'Surrey', 'Canada', 'Attacker', 2, '5 foot 6', '5/7/1990');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_STATE, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (5,5, 'Cincinnati', 'OH', 'USA', 'Midfielder', 10, '5 foot 4', '5/14/1995');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (6,6, 'Buenos Aires', 'Argentina', 'Midfielder', 10, '5 foot 3', '5/31/1994');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_STATE, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (7,7, 'Fort Lauderdale', 'FL', 'USA', 'Defender', 33, '6 foot 2', '3/3/1999');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_STATE, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (8,8, 'Columbus', 'OH', 'USA', 'Midfielder', 20, '5 foot 8', '1/15/1993');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (9,9, 'Remedios de Escalada', 'Argentina', 'Attacker', 15, '6 foot 1', '4/3/1997');

INSERT INTO TEAM_ROSTER(TEAM_ID, ATHLETE_ID, ATHLETE_CITY, ATHLETE_COUNTRY, ATHLETE_POSITION,
ATHLETE_NUMBER, ATHLETE_HEIGHT, ATHLETE_DOB) VALUES (10,10, 'Greenock', 'United Kingdon', 'Wing', 10, '5 foot 10', '9/30/1996');
