-- Chloe Jaiswal
-- 4/18/2022
-- Script to create roles, logins and assign permissions

-- Create login for system admin role
CREATE LOGIN JohnDoe
	WITH PASSWORD = 'Soccer2022!' MUST_CHANGE,
	CHECK_EXPIRATION = ON;
GO

-- Create system admin role
USE master;
CREATE SERVER ROLE nationalAdmin AUTHORIZATION JohnDoe;
GO

--------------------------------------------------------

-- Create NSA role
CREATE ROLE NSA;
-- Grants all permissions to NSA for objects
GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON ATHLETE TO NSA;
GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON ATHLETE_GAME_STATS TO NSA;
GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON SEASON_GAMES TO NSA;
GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON [STATS] TO NSA;
GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TEAM TO NSA;
GRANT ALTER, DELETE, INSERT, REFERENCES, SELECT, UPDATE ON TEAM_ROSTER TO NSA;
GRANT SELECT, VIEW DEFINITION ON ATHLETE TO NSA;
GRANT SELECT, VIEW DEFINITION ON ATHLETE_GAME_STATS TO NSA;
GRANT SELECT, VIEW DEFINITION ON SEASON_GAMES TO NSA;
GRANT SELECT, VIEW DEFINITION ON [STATS] TO NSA;
GRANT SELECT, VIEW DEFINITION ON TEAM TO NSA;
GRANT SELECT, VIEW DEFINITION ON TEAM_ROSTER TO NSA;
-- Create login for NSA role
CREATE LOGIN UnitedStates
	WITH PASSWORD = 'Soccer2022!' MUST_CHANGE,
	CHECK_EXPIRATION = ON;
GO

-- Creates Database user for United States
CREATE USER UnitedStates FOR LOGIN UnitedStates;
GO

-- Adds user United States to NSA role
ALTER ROLE NSA ADD MEMBER UnitedStates;
GO

----------------------------------------------------

-- Create Team role
CREATE ROLE Team;

-- Create log in for Team
CREATE LOGIN SanDiegoFC
	WITH PASSWORD = 'Soccer2022!' MUST_CHANGE,
	CHECK_EXPIRATION = ON;
GO

-- Creates database user for team
CREATE USER SanDiegoFC FOR LOGIN SanDiegoFC;
GO

-- Adds SanDiegoFC to team role
ALTER ROLE Team ADD MEMBER SanDiegoFC;
GO

-- Adds permissions to Team role for current database
GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ATHLETE TO TEAM;

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON ATHLETE_GAME_STATS TO TEAM;

GRANT DELETE, INSERT, SELECT, UPDATE, REFERENCES ON [STATS] TO TEAM;

GRANT INSERT, SELECT, UPDATE, REFERENCES ON TEAM TO TEAM;

GRANT SELECT, VIEW DEFINITION ON ATHLETE TO TEAM;
GRANT SELECT, VIEW DEFINITION ON ATHLETE_GAME_STATS TO TEAM;
GRANT SELECT, VIEW DEFINITION ON SEASON_GAMES TO TEAM;
GRANT SELECT, VIEW DEFINITION ON [STATS] TO TEAM;
GRANT SELECT, VIEW DEFINITION ON TEAM TO TEAM;
GRANT SELECT, VIEW DEFINITION ON TEAM_ROSTER TO TEAM;
------------------------------------------------

-- Create Manager role
CREATE ROLE Manager;

-- Create log in for Manager
CREATE LOGIN CaseyStone
	WITH PASSWORD = 'Soccer2022!' MUST_CHANGE,
	CHECK_EXPIRATION = ON;
GO

-- Creates database user for Manager
CREATE USER CaseyStone FOR LOGIN CaseyStone;
GO

-- Adds CaseyStone to Manager role
ALTER ROLE Manager ADD MEMBER CaseyStone;
GO

-- Adds permissions to Manager role
GRANT INSERT, SELECT, UPDATE, REFERENCES, VIEW DEFINITION ON TEAM_ROSTER TO MANAGER;
GRANT SELECT, VIEW DEFINITION ON ATHLETE TO MANAGER;
GRANT SELECT, VIEW DEFINITION ON ATHLETE_GAME_STATS TO MANAGER;
GRANT SELECT, VIEW DEFINITION ON SEASON_GAMES TO MANAGER;
GRANT SELECT, VIEW DEFINITION ON [STATS] TO MANAGER;
GRANT SELECT, VIEW DEFINITION ON TEAM TO MANAGER;
GRANT SELECT, VIEW DEFINITION ON TEAM_ROSTER TO MANAGER;
----------------------------------------

-- Create Fan role
CREATE ROLE Fan;

-- Create user without login
CREATE USER ChloeJaiswal WITHOUT LOGIN;
GO

-- Add user to fan role

ALTER ROLE FAN ADD MEMBER ChloeJaiswal;

-- Add permissions to allow viewing for anyone
GRANT SELECT, VIEW DEFINITION ON ATHLETE TO FAN;
GRANT SELECT, VIEW DEFINITION ON ATHLETE_GAME_STATS TO FAN;
GRANT SELECT, VIEW DEFINITION ON SEASON_GAMES TO FAN;
GRANT SELECT, VIEW DEFINITION ON [STATS] TO FAN;
GRANT SELECT, VIEW DEFINITION ON TEAM TO FAN;
GRANT SELECT, VIEW DEFINITION ON TEAM_ROSTER TO FAN;