/* Tests user defined function to parse together the first and last name
*/
USE Soccer
GO

SELECT dbo.FullName([ATHLETE_FIRST_NAME], [ATHLETE_LAST_NAME]) AS [Name],
[ATHLETE_AGE], TEAM_ROSTER.ATHLETE_CITY, TEAM_ROSTER.ATHLETE_STATE, 
TEAM_ROSTER.ATHLETE_COUNTRY, TEAM_ROSTER.ATHLETE_POSITION,
TEAM_ROSTER.ATHLETE_NUMBER, TEAM_ROSTER.ATHLETE_HEIGHT, TEAM_ROSTER.ATHLETE_DOB
FROM [ATHLETE], TEAM_ROSTER
WHERE ATHLETE.ATHLETE_ID = TEAM_ROSTER.ATHLETE_ID;
